### ISSUE TITLE
Stash doesn't save items?

### ISSUE THREAD

**Issue by merryymary** [Mustachedom/md-stashes#19]
I uploaded the sql file and did the newest release but when I put items in the stash it just teleports back to the inventory and the stash stays empty.

**Comment by Mustachedom** [comment]
This is addressed in the readme and is the fault of the inventory. 

My script simply makes a target and creates a stash uses events that inventories use. Once the inventory opens my script ends and the inventory script takes over

**Comment by merryymary** [comment]
Okay, I can look into it more, I was just confused because stashes in apartments and everything works, and this one works to open but not tos save items. I see that the export is the same line as the apartments export for stashes, so I'm honestly at a complete loss as to what is causing this issue :(

**Comment by merryymary** [comment]
Upon further testing, once I placed down one object stash one, it worked and all other location stashes that were created worked, but previous ones are still broken.
